export const LINE_CHART = 'LINE_CHART';
export const BAR_CHART = 'BAR_CHART';
export const HISTOGRAM_CHART = 'HISTOGRAM_CHART';

export const CHART_TYPES = [
  LINE_CHART,
  BAR_CHART,
  HISTOGRAM_CHART
];