const START_SELECTING_ITEMS = 'START_SELECTING_ITEMS';
const SELECT_ITEMS = 'SELECT_ITEMS';
const ADD_SCALE = 'ADD_SCALE';
const SELECT_SCALE = 'SELECT_SCALE';
const SET_SCALE_NAME = 'SET_SCALE_NAME';
const REMOVE_SCALE = 'REMOVE_SCALE';
const SET_MEASUREMENT_LEVEL = 'SET_MEASUREMENT_LEVEL';
const SET_SCALE_SCORES = 'SET_SCALE_SCORES';

export default {
  START_SELECTING_ITEMS,
  SELECT_ITEMS,
  ADD_SCALE,
  SELECT_SCALE,
  SET_SCALE_NAME,
  REMOVE_SCALE,
  SET_MEASUREMENT_LEVEL,
  SET_SCALE_SCORES
};