const ADD_TEST = 'ADD_TEST';
const SELECT_TEST = 'SELECT_TEST';
const SET_TESTS = 'SET_TESTS';
const START_SELECTING_SCALES = 'START_SELECTING_SCALES';
const SELECT_SCALES = 'SELECT_SCALES';
const SET_TEST_NAME = 'SET_TEST_NAME';
const REMOVE_TEST = 'REMOVE_TEST';
const SET_TEST_TYPE = 'SET_TEST_TYPE';

export default {
  ADD_TEST,
  SELECT_TEST,
  SET_TESTS,
  START_SELECTING_SCALES,
  SELECT_SCALES,
  SET_TEST_NAME,
  REMOVE_TEST,
  SET_TEST_TYPE
};