const NOTIFY_TESTS_RUNNING = 'NOTIFY_TESTS_RUNNING';
const NOTIFY_TEST_RESULTS = 'NOTIFY_TEST_RESULTS';
const NOTIFY_DESCRIPTIVES_RUNNING = 'NOTIFY_DESCRIPTIVES_RUNNING';
const NOTIFY_DESCRIPTIVES_RESULTS = 'NOTIFY_DESCRIPTIVES_RESULTS';

export default {
  NOTIFY_TESTS_RUNNING,
  NOTIFY_TEST_RESULTS,
  NOTIFY_DESCRIPTIVES_RUNNING,
  NOTIFY_DESCRIPTIVES_RESULTS
};
