const FILE_LOADING_START = 'FILE_LOADING_START';
const ITEM_NAMES_LOADED = 'ITEM_NAMES_LOADED';
const DATA_LOADED = 'DATA_LOADED';
const FILE_LOADING_END = 'FILE_LOADING_END';
const FILE_LOADING_ERROR = 'FILE_LOADING_ERROR';

export default {
  FILE_LOADING_START,
  ITEM_NAMES_LOADED,
  DATA_LOADED,
  FILE_LOADING_END,
  FILE_LOADING_ERROR
};